apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-xfusion
spec:
  template:
    metadata:
      name: countdown-xfusion
    spec:
      containers:
        - name: container-countdown-xfusion
          image: centos:latest
          command: ["/bin/sh", "-c"]
          args:
            [
              "for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
            ]
      restartPolicy: Never
