apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nautilus
  namespace: default
spec:
  schedule: "*/8 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-nautilus
            image: httpd:latest
            args: ['/bin/sh', '-c', 'date; echo Welcome to xfusioncorp!']
          restartPolicy: OnFailure