apiVersion: v1
kind: Service
metadata:
  name: node-service-datacenter
  namespace: node-namespace-datacenter
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - name: node-app
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-deployment-datacenter
  namespace: node-namespace-datacenter
  labels:
    app:  node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app:  node-app
    spec:
      containers:
      - name:  node-container-datacenter
        image:  gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort:  80
          name:  node-app
      restartPolicy: Always

kubectl create ns node-namespace-datacenter
