- hosts: all
  become: true
  tasks:
  - name: unzip data
    unarchive:
      src: /usr/src/dba/devops.zip
      dest: /opt/dba/
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"


- hosts: all
  become: true
  tasks:
  - name: add a file in a location set user & group permission
    ansible.builtin.file:
      path: /tmp/web.txt
      state: touch
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0744"



# Create a playbook.yml under /home/thor/ansible on jump host; an inventory file is already present under /home/thor/ansible directory on jump host itself.
# Create an empty file /opt/sysops/blog.txt on app server 1; its user owner and group owner should be tony. Create a symbolic link of source path /opt/sysops to destination /var/www/html.
# Create an empty file /opt/sysops/story.txt on app server 2; its user owner and group owner should be steve. Create a symbolic link of source path /opt/sysops to destination /var/www/html.
# Create an empty file /opt/sysops/media.txt on app server 3; its user owner and group owner should be banner. Create a symbolic link of source path /opt/sysops to destination /var/www/html.

- hosts: stapp01
  become: true
  tasks:
  - name: Create file on server1
    file:
      path: /opt/sysops/blog.txt
      state: touch
      owner: tony
      group: tony
      mode: "0777"  
  - name: Create a symbolic link
    file:
      src: /opt/sysops
      dest: /var/www/html
      owner: tony
      group: tony
      state: link
- hosts: stapp02
  become: true
  tasks:
  - name: Create file on server2
    file:
      path: /opt/sysops/story.txt
      state: touch
      owner: steve
      group: steve
      mode: "0777"  
  - name: Create a symbolic link
    file:
      src: /opt/sysops
      dest: /var/www/html
      owner: steve
      group: steve
      state: link
- hosts: stapp03
  become: true
  tasks:
  - name: Create file on server3
    file:
      path: /opt/sysops/media.txt
      state: touch
      owner: banner
      group: banner
      mode: "0777"  
  - name: Create a symbolic link
    file:
      src: /opt/sysops
      dest: /var/www/html
      owner: banner
      group: banner
      state: link



#using ansible conditionals
# Copy blog.txt file present under /usr/src/devops directory on jump host to App Server 1 under /opt/devops directory. Its user and group owner must be user tony and its permissions must be 0755 .

# Copy story.txt file present under /usr/src/devops directory on jump host to App Server 2 under /opt/devops directory. Its user and group owner must be user steve and its permissions must be 0755 .

# Copy media.txt file present under /usr/src/devops directory on jump host to App Server 3 under /opt/devops directory. Its user and group owner must be user banner and its permissions must be 0755 .

- hosts: all
  become: true
  tasks:
  - name: copy a file to a location set user & group permission
    ansible.builtin.copy:
      src: /usr/src/sysops/blog.txt
      dest: /opt/sysops
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0777"
    when: inventory_hostname == "stapp01"
  - name: copy a file to a location set user & group permission
    ansible.builtin.copy:
      src: /usr/src/sysops/story.txt
      dest: /opt/sysops
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0777"
    when: inventory_hostname == "stapp02"
  - name: copy a file to a location set user & group permission
    ansible.builtin.copy:
      src: /usr/src/sysops/media.txt
      dest: /opt/sysops
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0777"
    when: inventory_hostname == "stapp03"  

# To verify
ansible all -a "ls -ltr /opt/sysops" -i inventory



# Install httpd and php packages (whatever default version is available in yum repo)
# Change default document root of Apache to /var/www/html/myroot in default Apache config /etc/httpd/conf/httpd.conf. Make sure /var/www/html/myroot path exists (if not please create the same)

- name: Setup Httpd and PHP
  hosts: stapp02
  become: yes
  tasks:
    - name: Install latest version of httpd and php
      package:
        name:
          - httpd
          - php
        state: latest
    - name: Replace default DocumentRoot in httpd.conf
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: DocumentRoot \"\/var\/www\/html\"
        replace: DocumentRoot "/var/www/html/myroot"
    - name: Create the new DocumentRoot directory if it does not exist
      file:
        path: /var/www/html/myroot
        state: directory
        owner: apache
        group: apache
    - name: Use Jinja2 template to generate phpinfo.php
      template:
        src: /home/thor/playbooks/templates/phpinfo.php.j2
        dest: /var/www/html/myroot/phpinfo.php
        owner: apache
        group: apache
    - name: Start and enable service httpd
      service:
        name: httpd
        state: started
        enabled: yes 

---
- name: copy files to servers
  hosts: all
  become: yes
  tasks:
    - name: copying the files
      ansible.builtin.copy:
        src: /usr/src/devops/index.html
        dest: /opt/devops/index.html  # link to /path/to/file
        follow: no


- name: Ansible replace

  hosts: all

  become: yes

  tasks:

    - name: blog.txt replacement

      replace:

        path: /opt/data/blog.txt

        regexp: "xFusionCorp"

        replace: "Nautilus"

      when: inventory_hostname == "stapp01"

    - name: story.txt replacement

      replace:

        path: /opt/data/story.txt

        regexp: "Nautilus"

        replace: "KodeKloud"

      when: inventory_hostname == "stapp02"

    - name: media.txt replacement

      replace:

        path: /opt/data/media.txt

        regexp: "KodeKloud"

        replace: "xFusionCorp Industries"

      when: inventory_hostname == "stapp03"