- hosts: all
  become: true
  tasks:
  - name: unzip data
    unarchive:
      src: /usr/src/dba/devops.zip
      dest: /opt/dba/
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"




  
    
  