apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devops
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/finance

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devops
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-devops
spec:
  volumes:
    - name: storage-nautilus
      persistentVolumeClaim:
        claimName: pvc-devops
  containers:
    - name: container-devops
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: storage-nautilus
          mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Service
metadata:
  name: pod-devops
spec:
  selector: 
    name: pod-devops
  type: NodePort  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000